use raylib::prelude::*;
use raylib::ffi::KeyboardKey;

// esc,1,2,3,4,5,6,7,8,9,0,-,=,del,tab,q,w,e,r,t,y,u,i,o,p,[,],bkslsh,caps,a,s,d,
// f,g,h,j,k,l,;,',ent,lshft,z,x,c,v,b,n,m,comma,.,/,rshft,ctrl,~,alt,spc,ralt,up,down,left,right,

pub fn get_key_status(keycode: u8, rayhandle: &RaylibHandle) -> (bool, bool) {
    let key = match keycode {
        0 => KeyboardKey::KEY_ESCAPE,
        1 => KeyboardKey::KEY_ONE,
        2 => KeyboardKey::KEY_TWO,
        3 => KeyboardKey::KEY_THREE,
        4 => KeyboardKey::KEY_FOUR,
        5 => KeyboardKey::KEY_FIVE,
        6 => KeyboardKey::KEY_SIX,
        7 => KeyboardKey::KEY_SEVEN,
        8 => KeyboardKey::KEY_EIGHT,
        9 => KeyboardKey::KEY_NINE,
        10 => KeyboardKey::KEY_ZERO,
        11 => KeyboardKey::KEY_MINUS,
        12 => KeyboardKey::KEY_EQUAL,
        13 => KeyboardKey::KEY_BACKSPACE,
        14 => KeyboardKey::KEY_TAB,
        15 => KeyboardKey::KEY_Q,
        16 => KeyboardKey::KEY_W,
        17 => KeyboardKey::KEY_E,
        18 => KeyboardKey::KEY_R,
        19 => KeyboardKey::KEY_T,
        20 => KeyboardKey::KEY_Y,
        21 => KeyboardKey::KEY_U,
        22 => KeyboardKey::KEY_I,
        23 => KeyboardKey::KEY_O,
        24 => KeyboardKey::KEY_P,
        25 => KeyboardKey::KEY_LEFT_BRACKET,
        26 => KeyboardKey::KEY_RIGHT_BRACKET,
        27 => KeyboardKey::KEY_BACKSLASH,
        28 => KeyboardKey::KEY_CAPS_LOCK,
        29 => KeyboardKey::KEY_A,
        30 => KeyboardKey::KEY_S,
        31 => KeyboardKey::KEY_D,
        32 => KeyboardKey::KEY_F,
        33 => KeyboardKey::KEY_G,
        34 => KeyboardKey::KEY_H,
        35 => KeyboardKey::KEY_J,
        36 => KeyboardKey::KEY_K,
        37 => KeyboardKey::KEY_L,
        38 => KeyboardKey::KEY_SEMICOLON,
        39 => KeyboardKey::KEY_APOSTROPHE,
        40 => KeyboardKey::KEY_ENTER,
        41 => KeyboardKey::KEY_LEFT_SHIFT,
        42 => KeyboardKey::KEY_Z,
        43 => KeyboardKey::KEY_X,
        44 => KeyboardKey::KEY_C,
        45 => KeyboardKey::KEY_V,
        46 => KeyboardKey::KEY_B,
        47 => KeyboardKey::KEY_N,
        48 => KeyboardKey::KEY_M,
        49 => KeyboardKey::KEY_COMMA,
        50 => KeyboardKey::KEY_PERIOD,
        51 => KeyboardKey::KEY_SLASH,
        52 => KeyboardKey::KEY_RIGHT_SHIFT,
        53 => KeyboardKey::KEY_LEFT_CONTROL,
        54 => KeyboardKey::KEY_GRAVE,
        55 => KeyboardKey::KEY_LEFT_ALT,
        56 => KeyboardKey::KEY_SPACE,
        57 => KeyboardKey::KEY_RIGHT_ALT,
        58 => KeyboardKey::KEY_UP,
        59 => KeyboardKey::KEY_DOWN,
        60 => KeyboardKey::KEY_LEFT,
        61 => KeyboardKey::KEY_RIGHT,
        _ => panic!("unrecognized key code: {}", keycode),
    };
    (rayhandle.is_key_down(key), rayhandle.is_key_pressed(key) || rayhandle.is_key_released(key))
}